"""Geofence evaluation engine.

Checks vessel positions against active geofence zones and rules,
generating alerts when conditions are met.

The engine maintains an in-memory cache of active zones/rules and
tracks per-vessel state (entry time, last position) for stateful rules
like LOITER and EXIT.
"""

from __future__ import annotations

import logging
import math
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any

from okeanus.geofence.models import AlertSeverity, RuleType, ZoneType

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------

def _haversine_nm(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in nautical miles."""
    R_NM = 3440.065
    rlat1, rlat2 = math.radians(lat1), math.radians(lat2)
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) ** 2 + math.cos(rlat1) * math.cos(rlat2) * math.sin(dlon / 2) ** 2
    return 2 * R_NM * math.asin(math.sqrt(min(a, 1.0)))


def _point_in_polygon(lat: float, lon: float, polygon: list[list[float]]) -> bool:
    """Ray-casting point-in-polygon test.

    polygon: list of [lon, lat] pairs (GeoJSON convention).
    """
    n = len(polygon)
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = polygon[i][0], polygon[i][1]
        xj, yj = polygon[j][0], polygon[j][1]
        if ((yi > lat) != (yj > lat)) and (lon < (xj - xi) * (lat - yi) / (yj - yi) + xi):
            inside = not inside
        j = i
    return inside


def _point_in_zone(lat: float, lon: float, zone_type: str, geometry_data: dict) -> bool:
    """Check if a point is inside a geofence zone."""
    if zone_type == ZoneType.CIRCLE:
        center = geometry_data.get("center", [0, 0])
        radius_nm = geometry_data.get("radius_nm", 0)
        dist = _haversine_nm(lat, lon, center[1], center[0])
        return dist <= radius_nm
    elif zone_type == ZoneType.POLYGON:
        coords = geometry_data.get("coordinates", [[]])
        # GeoJSON polygon: first ring is exterior
        exterior = coords[0] if coords else []
        if len(exterior) < 3:
            return False
        return _point_in_polygon(lat, lon, exterior)
    return False


# ---------------------------------------------------------------------------
# Vessel state tracking
# ---------------------------------------------------------------------------

@dataclass
class VesselZoneState:
    """Per-vessel, per-zone tracking state."""
    mmsi: int
    zone_id: str
    is_inside: bool = False
    entry_time: datetime | None = None
    last_position_time: datetime | None = None
    last_lat: float = 0.0
    last_lon: float = 0.0
    last_sog: float = 0.0
    entry_alerted: bool = False
    exit_alerted: bool = False


@dataclass
class AlertEvent:
    """An alert generated by the engine (before persistence)."""
    zone_id: str
    zone_name: str
    rule_id: str
    rule_type: str
    severity: str
    mmsi: int
    triggered_at: datetime
    lat: float
    lon: float
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "zone_id": self.zone_id,
            "zone_name": self.zone_name,
            "rule_id": self.rule_id,
            "rule_type": self.rule_type,
            "severity": self.severity,
            "mmsi": str(self.mmsi),
            "triggered_at": self.triggered_at.isoformat(),
            "lat": round(self.lat, 5),
            "lon": round(self.lon, 5),
            "details": self.details,
        }


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

@dataclass
class ZoneConfig:
    """In-memory representation of a zone + its rules."""
    id: str
    name: str
    zone_type: str
    geometry_data: dict[str, Any]
    rules: list[dict[str, Any]] = field(default_factory=list)


class GeofenceEngine:
    """Stateful geofence evaluation engine.

    Maintains per-vessel zone state for stateful rules (LOITER, EXIT).
    Call evaluate() for each new vessel position to check all zones.
    """

    def __init__(self) -> None:
        self.zones: dict[str, ZoneConfig] = {}
        # State: (mmsi, zone_id) → VesselZoneState
        self._state: dict[tuple[int, str], VesselZoneState] = {}

    def load_zones(self, zones: list[ZoneConfig]) -> None:
        """Replace all zones with a new set."""
        self.zones = {z.id: z for z in zones}
        logger.info("Geofence engine loaded %d zones", len(self.zones))

    def add_zone(self, zone: ZoneConfig) -> None:
        """Add or update a single zone."""
        self.zones[zone.id] = zone

    def remove_zone(self, zone_id: str) -> None:
        """Remove a zone and clear associated state."""
        self.zones.pop(zone_id, None)
        keys_to_remove = [k for k in self._state if k[1] == zone_id]
        for k in keys_to_remove:
            del self._state[k]

    def evaluate(
        self,
        mmsi: int,
        lat: float,
        lon: float,
        sog: float,
        timestamp: datetime,
    ) -> list[AlertEvent]:
        """Evaluate a vessel position against all active zones.

        Returns a list of alerts triggered by this position.
        """
        alerts: list[AlertEvent] = []

        for zone_id, zone in self.zones.items():
            state_key = (mmsi, zone_id)
            state = self._state.get(state_key)
            if state is None:
                state = VesselZoneState(mmsi=mmsi, zone_id=zone_id)
                self._state[state_key] = state

            was_inside = state.is_inside
            is_inside = _point_in_zone(lat, lon, zone.zone_type, zone.geometry_data)
            state.is_inside = is_inside

            for rule in zone.rules:
                rule_type = rule.get("rule_type", "")
                rule_id = rule.get("id", "")
                severity = rule.get("severity", "warning")
                params = rule.get("parameters") or {}
                vessel_filter = rule.get("vessel_filter") or {}

                # Apply vessel filter
                if not self._matches_filter(mmsi, sog, vessel_filter):
                    continue

                # --- ENTRY ---
                if rule_type == RuleType.ENTRY and is_inside and not was_inside:
                    alerts.append(AlertEvent(
                        zone_id=zone_id, zone_name=zone.name,
                        rule_id=rule_id, rule_type=rule_type,
                        severity=severity, mmsi=mmsi,
                        triggered_at=timestamp, lat=lat, lon=lon,
                        details={"event": "vessel_entered_zone", "sog": sog},
                    ))
                    state.entry_time = timestamp
                    state.entry_alerted = True

                # --- EXIT ---
                elif rule_type == RuleType.EXIT and not is_inside and was_inside:
                    duration = 0.0
                    if state.entry_time:
                        duration = (timestamp - state.entry_time).total_seconds() / 60
                    alerts.append(AlertEvent(
                        zone_id=zone_id, zone_name=zone.name,
                        rule_id=rule_id, rule_type=rule_type,
                        severity=severity, mmsi=mmsi,
                        triggered_at=timestamp, lat=lat, lon=lon,
                        details={
                            "event": "vessel_exited_zone",
                            "time_in_zone_minutes": round(duration, 1),
                        },
                    ))
                    state.entry_time = None

                # --- LOITER ---
                elif rule_type == RuleType.LOITER and is_inside:
                    threshold_min = params.get("threshold_minutes", 60)
                    if state.entry_time is None:
                        state.entry_time = timestamp
                    duration = (timestamp - state.entry_time).total_seconds() / 60
                    if duration >= threshold_min:
                        alerts.append(AlertEvent(
                            zone_id=zone_id, zone_name=zone.name,
                            rule_id=rule_id, rule_type=rule_type,
                            severity=severity, mmsi=mmsi,
                            triggered_at=timestamp, lat=lat, lon=lon,
                            details={
                                "event": "vessel_loitering",
                                "duration_minutes": round(duration, 1),
                                "threshold_minutes": threshold_min,
                            },
                        ))
                        # Reset entry time to avoid repeated alerts every tick
                        state.entry_time = timestamp

                # --- SPEED ---
                elif rule_type == RuleType.SPEED and is_inside:
                    max_speed = params.get("max_speed_kn", 10.0)
                    if sog > max_speed:
                        alerts.append(AlertEvent(
                            zone_id=zone_id, zone_name=zone.name,
                            rule_id=rule_id, rule_type=rule_type,
                            severity=severity, mmsi=mmsi,
                            triggered_at=timestamp, lat=lat, lon=lon,
                            details={
                                "event": "speed_violation",
                                "vessel_speed_kn": sog,
                                "max_speed_kn": max_speed,
                            },
                        ))

                # --- AIS_OFF ---
                elif rule_type == RuleType.AIS_OFF and is_inside:
                    gap_hours = params.get("gap_hours", 6)
                    if state.last_position_time:
                        gap = (timestamp - state.last_position_time).total_seconds() / 3600
                        if gap >= gap_hours:
                            alerts.append(AlertEvent(
                                zone_id=zone_id, zone_name=zone.name,
                                rule_id=rule_id, rule_type=rule_type,
                                severity=severity, mmsi=mmsi,
                                triggered_at=timestamp, lat=lat, lon=lon,
                                details={
                                    "event": "ais_gap_in_zone",
                                    "gap_hours": round(gap, 1),
                                    "threshold_hours": gap_hours,
                                },
                            ))

            # Reset entry tracking on exit
            if not is_inside and was_inside:
                state.entry_time = None

            # Track entry for new zone entry
            if is_inside and not was_inside:
                state.entry_time = timestamp

            # Update position state
            state.last_position_time = timestamp
            state.last_lat = lat
            state.last_lon = lon
            state.last_sog = sog

        return alerts

    def evaluate_batch(
        self,
        positions: list[dict[str, Any]],
    ) -> list[AlertEvent]:
        """Evaluate a batch of vessel positions.

        Each position dict: {"mmsi": int, "lat": float, "lon": float,
                             "sog": float, "timestamp": datetime}
        """
        all_alerts: list[AlertEvent] = []
        for pos in positions:
            alerts = self.evaluate(
                mmsi=pos["mmsi"],
                lat=pos["lat"],
                lon=pos["lon"],
                sog=pos.get("sog", 0.0),
                timestamp=pos["timestamp"],
            )
            all_alerts.extend(alerts)
        return all_alerts

    @staticmethod
    def _matches_filter(mmsi: int, sog: float, vessel_filter: dict) -> bool:
        """Check if a vessel matches the optional filter criteria."""
        if not vessel_filter:
            return True
        mmsi_list = vessel_filter.get("mmsi_list")
        if mmsi_list and mmsi not in mmsi_list:
            return False
        return True

    def get_state(self, mmsi: int) -> list[dict[str, Any]]:
        """Get current zone state for a vessel."""
        results = []
        for (m, zone_id), state in self._state.items():
            if m == mmsi:
                zone = self.zones.get(zone_id)
                results.append({
                    "zone_id": zone_id,
                    "zone_name": zone.name if zone else "unknown",
                    "is_inside": state.is_inside,
                    "entry_time": state.entry_time.isoformat() if state.entry_time else None,
                    "last_position_time": (
                        state.last_position_time.isoformat() if state.last_position_time else None
                    ),
                })
        return results

    def clear_state(self) -> None:
        """Clear all vessel tracking state."""
        self._state.clear()


# Singleton engine instance
_engine: GeofenceEngine | None = None


def get_geofence_engine() -> GeofenceEngine:
    """Get or create the singleton geofence engine."""
    global _engine
    if _engine is None:
        _engine = GeofenceEngine()
    return _engine
